### ISSUE TITLE
Pure virtual functions

### ISSUE THREAD

**Issue by vwengert** [eriks47/generate.nvim#2]
Generate implementations also creates pure virtual functions in the source file.

```
class Test
{
  public:
    Test();

    virtual ~Test() = 0;
    virtual void draw() const = 0;
};
```
generates
```
#include "test.h"



Test::Test()
{

}

Test::~Test() = 0
{

}

void Test::draw() const = 0
{

}
```

**Comment by eriks47** [comment]
I replicated the issue. I will certainly look into it later today.

**Comment by eriks47** [comment]
The last commit seems to solve the issue; however the solution is somewhat shaky, because, unfortunately, the Treesitter C++ parser often creates an "ERROR" node when faced with a pure virtual function. Make sure to let me know if the issue persists or if you find other cases in which the plugin misbehaves.

**Comment by vwengert** [comment]
Love it, works great for me
